# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [ commit ]
exclude: ^.venv/|^venv/|^.pytest_cache|^reports|\.bin|\.tgz
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=1500']
    -   id: check-ast
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        language_version: python3.10
        args: ["--line-length=80"]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--ignore=F405", "--max-line-length=80"]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length=80"]
