networks:
  e2e:
    driver: bridge

services:

  allure:
    image: "frankescobar/allure-docker-service"
    container_name: allure
    restart: unless-stopped
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 20
    ports:
      - "5050:5050"
    volumes:
      - ./reports:/app/projects:rw
    networks:
      - e2e

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    container_name: "allure-ui"
    restart: unless-stopped
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    depends_on:
      - allure
    ports:
      - "5252:5252"
    networks:
      - e2e
